/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.efg;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/gradle_tomcat")
public class SimpleServlet extends HttpServlet {
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/plain;charset=utf-8");
        response.getWriter().print("Gradle War Plugin deploy to Tomcat");
    }

    protected boolean isServlet() {
    	return true;
    }
}